on: [push]

jobs:
  lcov:
    runs-on: ubuntu-latest
    name: Bun Lcov Test
    steps:
      - uses: actions/checkout@v4
      - uses: IDScript/DevOps/lcov@v0.0.2-11
        with:
          coverage-files: coverage/lcov.info
          working-dir: bun
